apiVersion: v1
kind: Namespace
metadata:
  name: resource-demo

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: resource-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: resource-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 200m
              memory: 256Mi
